[features]
seeds = false
[programs.devnet]
nft_presale = "EBo6LU66bXznJPUdySb4Rh9uZMNcwJF1gWkwuyWRMxcP"
[programs.localnet]
nft_presale = "EBo6LU66bXznJPUdySb4Rh9uZMNcwJF1gWkwuyWRMxcP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/sotatek/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
